from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class GenerateRequest(BaseModel):
    prompt: str = Field(..., title="Prompt text", description="The input text prompt for the AI model.", min_length=1)
    tone: str = Field("Standard", title="Output Tone", description="The requested writing tone or persona.")
    max_tokens: int = Field(100, title="Max Tokens", description="Maximum number of tokens to generate.", gt=0)
    session_id: Optional[str] = Field(None, title="Session ID", description="The chat session ID if continuing an existing conversation.")

class GenerateResponse(BaseModel):
    result: str = Field(..., title="Generated Result", description="The text generated by the AI model.")
    tokens_used: int = Field(..., title="Tokens Used", description="Number of tokens used in the generation.")

class ChatSessionCreate(BaseModel):
    title: str = Field("New Chat", title="Title", description="The title of the chat session.")

class ChatSessionResponse(BaseModel):
    id: str
    title: str
    created_at: str
    updated_at: str

class ChatMessageResponse(BaseModel):
    id: int
    role: str
    content: str
    citations: Optional[Any] = None
    created_at: str
